source "https://rubygems.org"

ruby "2.2.2"

gem "rails", "~> 5.1.0"
gem "active_model_serializers", "~> 0.10.6"
gem "aws-sdk", "~> 2.3.0"
gem "cocoon"
gem "email_validator"
gem "flutie"
gem "high_voltage"
gem "highcharts-rails"
gem "jquery-rails"
gem "neat", "~> 1.7.0"
gem "normalize-rails"
gem "paperclip", "~> 5.1.0"
gem "paper_trail"
gem "pg"
gem "puma"
gem "pundit"
gem "rack-cors"
gem "record_tag_helper"
gem "rest-client"
gem "sass-rails"
gem "simple_form"
gem "roles_db", git: "git@github.com:MIT-IR/roles_db.git"
gem "scenic"
gem "selectize-rails", "~>0.11.0"
gem "therubyracer"
gem "title"
gem "uglifier"
gem "autoprefixer-rails"
gem "font-awesome-rails"
gem "inline_svg"

group :development do
  gem "browser_sync_rails"
  gem "capistrano-rails"
  gem "capistrano-rvm"
  gem "gssapi", git: "git@github.com:derekprior/gssapi.git"
  gem "net-ssh-krb"
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "capybara-selenium"
  gem "launchy"
  gem "shoulda-matchers"
end

group :development, :test do
  gem "awesome_print"
  gem "bundler-audit", require: false
  gem "byebug"
  gem "factory_girl_rails"
  gem "pry-rails"
  gem "rspec-core", github: "rspec/rspec-core"
  gem "rspec-mocks", github: "rspec/rspec-mocks"
  gem "rspec-expectations", github: "rspec/rspec-expectations"
  gem "rspec-support", github: "rspec/rspec-support"
  gem "rspec-rails", github: "rspec/rspec-rails", branch: "integrate-with-system-test"
end
